spring:
  profiles:
    active: "dev"

---

spring:
  profiles: dev
  datasource:
    url: 'jdbc:mysql://localhost:3306/smellylist_dev'
    username: smellylist_dev_user
    password: smellylist_dev_pwd
  jpa:
    hibernate:
      ddl-auto: none
server:
  port : 8080
  servlet:
    contextPath : /api
jwt:
  issuer: SmellyList
  access:
    expiry:
      minutes: 30
    secret: todo-access-dev-secret-change-in-prod
  refresh:
    expiry:
      days: 28
    secret: todo-refresh-dev-secret-change-in-prod
